/* Generated by Nim Compiler v0.11.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, i386, gcc */
/* Command for C compiler:
   gcc.exe -c  -w  -IC:\Nim\lib -o d:\nim\2015-7-30\nimcache\stdlib_strutils.o d:\nim\2015-7-30\nimcache\stdlib_strutils.c */
#define NIM_INTBITS 32
#include "nimbase.h"

#include <string.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NI Skiptable98721[256];
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(NIM_CHAR, nsuToLowerChar)(NIM_CHAR c);
static N_INLINE(NI, addInt)(NI a, NI b);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_20001)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(void, preprocesssub_98727)(NimStringDesc* sub, NI* a);
N_NIMCALL(NI, findaux_98795)(NimStringDesc* s, NimStringDesc* sub, NI start, Skiptable98721 a);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start_76643, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_NIMCALL(NimStringDesc*, copyStr)(NimStringDesc* s, NI start);
N_NIMCALL(NimStringDesc*, copyStr)(NimStringDesc* s, NI first);
STRING_LITERAL(TMP146, "", 0);
extern TFrame* frameptr_17042;

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (a <= i);
		if (!(LOC3)) goto LA4;
		LOC3 = (i <= b);
		LA4: ;
		if (!LOC3) goto LA5;
		result = i;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU32)(a) - (NU32)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ (NI)((NU32) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU32)(a) + (NU32)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_17042 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_17042).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_17042;
	frameptr_17042 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_20001();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_17042 = (*frameptr_17042).prev;
}

N_NIMCALL(NIM_CHAR, nsuToLowerChar)(NIM_CHAR c) {
	NIM_CHAR result;
	nimfr("toLower", "strutils.nim")
	result = 0;
	nimln(69, "strutils.nim");
	{
		NI TMP144;
		if (!(((NU8)(c)) >= ((NU8)(65)) && ((NU8)(c)) <= ((NU8)(90)))) goto LA3;
		nimln(70, "strutils.nim");
		TMP144 = addInt(((NI) (((NU8)(c)))), ((NI) 32));
		result = ((NIM_CHAR) (((NI)chckRange((NI)(TMP144), ((NI) 0), ((NI) 255)))));
	}
	goto LA1;
	LA3: ;
	{
		nimln(72, "strutils.nim");
		result = c;
	}
	LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, nsuToLowerStr)(NimStringDesc* s) {
	NimStringDesc* result;
	nimfr("toLower", "strutils.nim")
	result = 0;
	nimln(81, "strutils.nim");
	result = mnewString(((NI)chckRange((s ? s->Sup.len : 0), ((NI) 0), ((NI) 2147483647))));
	{
		NI i_96091;
		NI HEX3Atmp_96093;
		NI TMP143;
		NI res_96096;
		i_96091 = 0;
		HEX3Atmp_96093 = 0;
		nimln(82, "strutils.nim");
		TMP143 = subInt((s ? s->Sup.len : 0), ((NI) 1));
		HEX3Atmp_96093 = (NI)(TMP143);
		nimln(1598, "system.nim");
		res_96096 = ((NI) 0);
		{
			nimln(1599, "system.nim");
			while (1) {
				NI TMP145;
				if (!(res_96096 <= HEX3Atmp_96093)) goto LA3;
				nimln(1600, "system.nim");
				i_96091 = res_96096;
				nimln(83, "strutils.nim");
				if ((NU)(i_96091) > (NU)(result->Sup.len)) raiseIndexError();
				if ((NU)(i_96091) > (NU)(s->Sup.len)) raiseIndexError();
				result->data[i_96091] = nsuToLowerChar(s->data[i_96091]);
				nimln(1619, "system.nim");
				TMP145 = addInt(res_96096, ((NI) 1));
				res_96096 = (NI)(TMP145);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

N_NIMCALL(void, preprocesssub_98727)(NimStringDesc* sub, NI* a) {
	NI m;
	nimfr("preprocessSub", "strutils.nim")
	nimln(768, "strutils.nim");
	m = (sub ? sub->Sup.len : 0);
	{
		NI i_98744;
		NI res_98759;
		i_98744 = 0;
		nimln(1598, "system.nim");
		res_98759 = ((NI) 0);
		{
			nimln(1599, "system.nim");
			while (1) {
				NI TMP147;
				NI TMP148;
				if (!(res_98759 <= ((NI) 255))) goto LA3;
				nimln(1600, "system.nim");
				i_98744 = res_98759;
				nimln(769, "strutils.nim");
				TMP147 = addInt(m, ((NI) 1));
				a[(((NU8)(((NIM_CHAR) (((NI)chckRange(i_98744, ((NI) 0), ((NI) 255))))))))- 0] = (NI)(TMP147);
				nimln(1619, "system.nim");
				TMP148 = addInt(res_98759, ((NI) 1));
				res_98759 = (NI)(TMP148);
			} LA3: ;
		}
	}
	{
		NI i_98755;
		NI HEX3Atmp_98764;
		NI TMP149;
		NI res_98767;
		i_98755 = 0;
		HEX3Atmp_98764 = 0;
		nimln(770, "strutils.nim");
		TMP149 = subInt(m, ((NI) 1));
		HEX3Atmp_98764 = (NI)(TMP149);
		nimln(1598, "system.nim");
		res_98767 = ((NI) 0);
		{
			nimln(1599, "system.nim");
			while (1) {
				NI TMP150;
				NI TMP151;
				if (!(res_98767 <= HEX3Atmp_98764)) goto LA6;
				nimln(1600, "system.nim");
				i_98755 = res_98767;
				nimln(770, "strutils.nim");
				if ((NU)(i_98755) > (NU)(sub->Sup.len)) raiseIndexError();
				TMP150 = subInt(m, i_98755);
				a[(((NU8)(sub->data[i_98755])))- 0] = (NI)(TMP150);
				nimln(1619, "system.nim");
				TMP151 = addInt(res_98767, ((NI) 1));
				res_98767 = (NI)(TMP151);
			} LA6: ;
		}
	}
	popFrame();
}

N_NIMCALL(NI, findaux_98795)(NimStringDesc* s, NimStringDesc* sub, NI start, Skiptable98721 a) {
	NI result;
	NI m;
	NI n;
	NI j;
	nimfr("findAux", "strutils.nim")
{	result = 0;
	nimln(775, "strutils.nim");
	m = (sub ? sub->Sup.len : 0);
	nimln(776, "strutils.nim");
	n = (s ? s->Sup.len : 0);
	nimln(778, "strutils.nim");
	j = start;
	{
		nimln(779, "strutils.nim");
		while (1) {
			NI TMP152;
			NI TMP156;
			NI TMP157;
			TMP152 = subInt(n, m);
			if (!(j <= (NI)(TMP152))) goto LA2;
			{
				{
					NI k_98816;
					NI HEX3Atmp_98828;
					NI TMP153;
					NI res_98831;
					k_98816 = 0;
					HEX3Atmp_98828 = 0;
					nimln(781, "strutils.nim");
					TMP153 = subInt(m, ((NI) 1));
					HEX3Atmp_98828 = (NI)(TMP153);
					nimln(1598, "system.nim");
					res_98831 = ((NI) 0);
					{
						nimln(1599, "system.nim");
						while (1) {
							NI TMP155;
							if (!(res_98831 <= HEX3Atmp_98828)) goto LA6;
							nimln(1600, "system.nim");
							k_98816 = res_98831;
							nimln(782, "strutils.nim");
							{
								NI TMP154;
								if ((NU)(k_98816) > (NU)(sub->Sup.len)) raiseIndexError();
								TMP154 = addInt(k_98816, j);
								if ((NU)((NI)(TMP154)) > (NU)(s->Sup.len)) raiseIndexError();
								if (!!(((NU8)(sub->data[k_98816]) == (NU8)(s->data[(NI)(TMP154)])))) goto LA9;
								goto LA3;
							}
							LA9: ;
							nimln(1619, "system.nim");
							TMP155 = addInt(res_98831, ((NI) 1));
							res_98831 = (NI)(TMP155);
						} LA6: ;
					}
				}
				nimln(783, "strutils.nim");
				result = j;
				goto BeforeRet;
			} LA3: ;
			nimln(784, "strutils.nim");
			TMP156 = addInt(j, m);
			if ((NU)((NI)(TMP156)) > (NU)(s->Sup.len)) raiseIndexError();
			TMP157 = addInt(j, a[(((NU8)(s->data[(NI)(TMP156)])))- 0]);
			j = (NI)(TMP157);
		} LA2: ;
	}
	nimln(785, "strutils.nim");
	result = ((NI) -1);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI)((*src).Sup.len + ((NI) 1)));
	(*dest).Sup.len += (*src).Sup.len;
}

N_NIMCALL(NimStringDesc*, nsuReplaceStr)(NimStringDesc* s, NimStringDesc* sub, NimStringDesc* by) {
	NimStringDesc* result;
	Skiptable98721 a;
	NI i;
	NimStringDesc* LOC8;
	nimfr("replace", "strutils.nim")
	result = 0;
	nimln(896, "strutils.nim");
	result = copyString(((NimStringDesc*) &TMP146));
	nimln(897, "strutils.nim");
	preprocesssub_98727(sub, a);
	nimln(898, "strutils.nim");
	i = ((NI) 0);
	{
		nimln(899, "strutils.nim");
		while (1) {
			NI j;
			NI TMP158;
			NimStringDesc* LOC7;
			NI TMP159;
			nimln(900, "strutils.nim");
			j = findaux_98795(s, sub, i, a);
			nimln(901, "strutils.nim");
			{
				if (!(j < ((NI) 0))) goto LA5;
				goto LA1;
			}
			LA5: ;
			nimln(902, "strutils.nim");
			TMP158 = subInt(j, ((NI) 1));
			LOC7 = 0;
			LOC7 = copyStrLast(s, i, (NI)(TMP158));
			result = resizeString(result, LOC7->Sup.len + 0);
appendString(result, LOC7);
			nimln(903, "strutils.nim");
			result = resizeString(result, by->Sup.len + 0);
appendString(result, by);
			nimln(904, "strutils.nim");
			TMP159 = addInt(j, (sub ? sub->Sup.len : 0));
			i = (NI)(TMP159);
		}
	} LA1: ;
	nimln(906, "strutils.nim");
	LOC8 = 0;
	LOC8 = copyStr(s, i);
	result = resizeString(result, LOC8->Sup.len + 0);
appendString(result, LOC8);
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit)(void) {
	nimfr("strutils", "strutils.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit)(void) {
}

